[tool.poetry]
name = "hardestclimbs.com"
version = "0.1.0"
description = "A website for the hardest climbs in the world"
authors = ["Dev <admin@hardestclimbs.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.3"
jsonschema = "^4.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
