name: CI

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      # Install Poetry
      - name: Install Poetry
        run: pip install poetry==1.8.3
      
      # Install dependencies
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Validate JSON
        run: python src/validate_json.py

      - name: Validate CSVs
        run: python src/validate_csv.py
