name: CI

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      
      # Install uv
      - name: Install uv
        run: pip install uv==0.6.13
      
      - name: Validate JSON
        run: uv run src/validate_json.py

      - name: Validate CSVs
        run: uv run src/validate_csv.py
